export const SET_NAME = "SET_NAME";

export const SET_SCREEN_SHARING = "SET_SCREEN_SHARING";
export const SET_SCREEN_SHARING_REQUESTED = "SET_SCREEN_SHARING_REQUESTED";
export const SET_SCREEN_SHARING_STREAM = "SET_SCREEN_SHARING_STREAM";
